name: My First CI

on:
  push:
    branches: [ master ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Say Hello
        run: echo "🎉 Hello from CI/CD!"
